on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v4

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Cargo Binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install Trunk
        run: cargo binstall trunk

      - uses: automas-dev/reusable-workflows/increment_version@v1.1
        id: version
        with:
          dry-run: true

      - name: Get Next Version
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: sed -i "/^version/c\version = \"$VERSION\"" Cargo.toml

      - name: Build Site
        run: trunk build --release

      - name: Upload dist files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      # - name: Create Tag
      #   uses: automas-dev/reusable-workflows/increment_version@v1.0
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     tag: ${{ steps.version.outputs.version }}

      - name: Deploy Site to GitHub Pages
        # if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
